Pre Processing - Defining NOC Grouping Identifers for TS forecasting

In [ ]:
'''
The purpose of this notebook is to determine the identifiers for the NOC Grouping and the 
occupations that were grouped into them.
'''

In [1]:
import pandas as pd

In [2]:
df_Dimension = pd.read_csv('metadata/14100421_MetaData_Dimensions.csv')
df_Dimension

   Dimension ID                              Dimension name
0             1                                   Geography
1             2                Labour force characteristics
2             3  National Occupational Classification (NOC)
3             4                                      Gender

In [3]:
#We are interested in Dimension 3 

df_Members = pd.read_csv('metadata/14100421_MetaData_Members.csv')
df_Members

,Dimension ID,Member Name,Classification Code,Member ID,Parent Member ID,Terminated,Member Notes
0,1,Canada,[11124],1,NaN,NaN,NaN
1,1,Newfoundland and Labrador,[10],2,1.0,NaN,NaN
2,1,Prince Edward Island,[11],3,1.0,NaN,NaN
3,1,Nova Scotia,[12],4,1.0,NaN,NaN
4,1,New Brunswick,[13],5,1.0,NaN,NaN
...,...,...,...,...,...,...,...
75,3,"Labourers in processing, manufacturing and uti...",[95],59,56.0,NaN,NaN
76,3,Unclassified occupations,NaN,60,1.0,NaN,11.0
77,4,Total - Gender,NaN,1,NaN,NaN,NaN
78,4,Men+,NaN,2,1.0,NaN,NaN
79,4,Women+,NaN,3,1.0,NaN,NaN

In [4]:
df_Members_Reduced = df_Members[df_Members['Dimension ID']==3][['Member Name','Member ID','Member Notes']]
df_Members_Reduced

                                          Member Name  Member ID  Member Notes
17                             Total, all occupations          1          10.0
18                             Management occupations          2          14.0
19      Legislative and senior management occupations          3           NaN
20          Specialized middle management occupations          4          15.0
21  Middle management occupations in retail and wh...          5           NaN
22  Middle management occupations in trades, trans...          6          16.0
23  Business, finance and administration occupatio...          7          17.0
24   Professional occupations in finance and business          8           NaN
25                Professional occupations in finance          9           NaN
26               Professional occupations in business         10           NaN
27  Administrative and financial supervisors and s...         11           NaN
28  Administrative occupations and transportation ...         12           NaN
29  Administrative and financial support and suppl...         13           NaN
30  Natural and applied sciences and related occup...         14          18.0
31  Professional occupations in natural and applie...         15           NaN
32       Professional occupations in natural sciences         16           NaN
33  Professional occupations in applied sciences (...         17           NaN
34            Professional occupations in engineering         18           NaN
35  Technical occupations related to natural and a...         19           NaN
36              Health occupations, except management         20          19.0
37                 Professional occupations in health         21           NaN
38  Health treating and consultation services prof...         22           NaN
39               Therapy and assessment professionals         23           NaN
40            Nursing and allied health professionals         24           NaN
41                    Technical occupations in health         25           NaN
42  Assisting occupations in support of health ser...         26           NaN
43  Occupations in education, law and social, comm...         27          20.0
44  Professional occupations in law, education, so...         28           NaN
45                    Professional occupations in law         29           NaN
46     Professional occupations in education services         30           NaN
47  Professional occupations in social and communi...         31           NaN
48    Professional occupations in government services         32           NaN
49  Front-line public protection services and para...         33           NaN
50  Occupations in front-line public protection se...         34           NaN
51  Paraprofessional occupations in legal, social,...         35           NaN
52  Assisting occupations in education and in lega...         36           NaN
53  Care providers and public protection support o...         37          21.0
54  Occupations in art, culture, recreation and sp...         38          22.0
55        Professional occupations in art and culture         39           NaN
56    Technical occupations in art, culture and sport         40           NaN
57              Occupations in art, culture and sport         41           NaN
58      Support occupations in art, culture and sport         42          23.0
59   Sales and service occupations, except management         43          24.0
60  Retail sales and service supervisors and speci...         44           NaN
61                  Occupations in sales and services         45           NaN
62  Sales and service representatives and other cu...         46           NaN
63              Sales and service support occupations         47           NaN
64  Trades, transport and equipment operators and ...         48          25.0
65  Technical trades and transportation officers a...         49           NaN
66                                     General trades         50           NaN
67  Mail and message distribution, other transport...         51           NaN
68  Helpers and labourers and other transport driv...         52           NaN
69  Natural resources, agriculture and related pro...         53          26.0
70  Supervisors and occupations in natural resourc...         54          27.0
71  Workers and labourers in natural resources, ag...         55          28.0
72  Occupations in manufacturing and utilities, ex...         56          29.0
73  Supervisors, central control and process opera...         57          30.0
74  Machine operators, assemblers and inspectors i...         58           NaN
75  Labourers in processing, manufacturing and uti...         59           NaN
76                           Unclassified occupations         60          11.0

In [5]:
df_Notes = pd.read_csv('metadata/14100421_MetaData_Notes.csv')
df_Notes

    Note ID                                               Note
0         1  To ensure respondent confidentiality, estimate...
1         2  For approximate quality indicators of the esti...
2         3  Number of civilian, non-institutionalized pers...
3         4  Number of persons who, during the reference we...
4         5  Full-time employment consists of persons who u...
5         6  Part-time employment consists of persons who u...
6         7  Number of persons who, during the reference we...
7         8  The unemployment rate is the number of unemplo...
8         9  Occupation estimates are based on the 2021 Nat...
9        10  This combines the National Occupational Classi...
10       11  Unemployed persons who have never worked befor...
11       12  This new table replaces archived table 14-10-0...
12       13                         Excluding the territories.
13       14  This combines the National Occupational Classi...
14       15  This combines the National Occupational Classi...
15       16  This combines the National Occupational Classi...
16       17  This combines the National Occupational Classi...
17       18  This combines the National Occupational Classi...
18       19  This combines the National Occupational Classi...
19       20  This combines the National Occupational Classi...
20       21  This combines the National Occupational Classi...
21       22  This combines the National Occupational Classi...
22       23  This combines the National Occupational Classi...
23       24  This combines the National Occupational Classi...
24       25  This combines the National Occupational Classi...
25       26  This combines the National Occupational Classi...
26       27  This combines the National Occupational Classi...
27       28  This combines the National Occupational Classi...
28       29  This combines the National Occupational Classi...
29       30  This combines the National Occupational Classi...
30       31  Starting in 2006, enhancements to the Labour F...
31       32  Gender refers to an individual's personal and ...
32       33  Given that the non-binary population is small,...

In [9]:
NoteID_Dict = df_Notes.set_index('Note ID')['Note'].to_dict()

In [10]:
df_Members_Reduced['Grouping Notes'] = df_Members_Reduced['Member Notes'].map(NoteID_Dict)
df_Members_Reduced

,Member Name,Member ID,Member Notes,Grouping Notes
17,"Total, all occupations",1,10.0,This combines the National Occupational Classi...
18,Management occupations,2,14.0,This combines the National Occupational Classi...
19,Legislative and senior management occupations,3,NaN,NaN
20,Specialized middle management occupations,4,15.0,This combines the National Occupational Classi...
21,Middle management occupations in retail and wh...,5,NaN,NaN
22,"Middle management occupations in trades, trans...",6,16.0,This combines the National Occupational Classi...
23,"Business, finance and administration occupatio...",7,17.0,This combines the National Occupational Classi...
24,Professional occupations in finance and business,8,NaN,NaN
25,Professional occupations in finance,9,NaN,NaN
26,Professional occupations in business,10,NaN,NaN
27,Administrative and financial supervisors and s...,11,NaN,NaN
28,Administrative occupations and transportation ...,12,NaN,NaN
29,Administrative and financial support and suppl...,13,NaN,NaN
30,Natural and applied sciences and related occup...,14,18.0,This combines the National Occupational Classi...
31,Professional occupations in natural and applie...,15,NaN,NaN
32,Professional occupations in natural sciences,16,NaN,NaN
33,Professional occupations in applied sciences (...,17,NaN,NaN
34,Professional occupations in engineering,18,NaN,NaN
35,Technical occupations related to natural and a...,19,NaN,NaN
36,"Health occupations, except management",20,19.0,This combines the National Occupational Classi...
37,Professional occupations in health,21,NaN,NaN
38,Health treating and consultation services prof...,22,NaN,NaN
39,Therapy and assessment professionals,23,NaN,NaN
40,Nursing and allied health professionals,24,NaN,NaN
41,Technical occupations in health,25,NaN,NaN
42,Assisting occupations in support of health ser...,26,NaN,NaN
43,"Occupations in education, law and social, comm...",27,20.0,This combines the National Occupational Classi...
44,"Professional occupations in law, education, so...",28,NaN,NaN
45,Professional occupations in law,29,NaN,NaN
46,Professional occupations in education services,30,NaN,NaN
47,Professional occupations in social and communi...,31,NaN,NaN
48,Professional occupations in government services,32,NaN,NaN
49,Front-line public protection services and para...,33,NaN,NaN
50,Occupations in front-line public protection se...,34,NaN,NaN
51,"Paraprofessional occupations in legal, social,...",35,NaN,NaN
52,Assisting occupations in education and in lega...,36,NaN,NaN
53,Care providers and public protection support o...,37,21.0,This combines the National Occupational Classi...
54,"Occupations in art, culture, recreation and sp...",38,22.0,This combines the National Occupational Classi...
55,Professional occupations in art and culture,39,NaN,NaN
56,"Technical occupations in art, culture and sport",40,NaN,NaN
57,"Occupations in art, culture and sport",41,NaN,NaN
58,"Support occupations in art, culture and sport",42,23.0,This combines the National Occupational Classi...
59,"Sales and service occupations, except management",43,24.0,This combines the National Occupational Classi...
60,Retail sales and service supervisors and speci...,44,NaN,NaN
61,Occupations in sales and services,45,NaN,NaN
62,Sales and service representatives and other cu...,46,NaN,NaN
63,Sales and service support occupations,47,NaN,NaN
64,"Trades, transport and equipment operators and ...",48,25.0,This combines the National Occupational Classi...
65,Technical trades and transportation officers a...,49,NaN,NaN
66,General trades,50,NaN,NaN
67,"Mail and message distribution, other transport...",51,NaN,NaN
68,Helpers and labourers and other transport driv...,52,NaN,NaN
69,"Natural resources, agriculture and related pro...",53,26.0,This combines the National Occupational Classi...
70,Supervisors and occupations in natural resourc...,54,27.0,This combines the National Occupational Classi...
71,"Workers and labourers in natural resources, ag...",55,28.0,This combines the National Occupational Classi...
72,"Occupations in manufacturing and utilities, ex...",56,29.0,This combines the National Occupational Classi...
73,"Supervisors, central control and process opera...",57,30.0,This combines the National Occupational Classi...
74,"Machine operators, assemblers and inspectors i...",58,NaN,NaN
75,"Labourers in processing, manufacturing and uti...",59,NaN,NaN
76,Unclassified occupations,60,11.0,Unemployed persons who have never worked befor...

In [11]:
df_Final_Tbl_NOC_Grouping_ID = df_Members_Reduced[['Member Name', 'Member ID', 'Grouping Notes']].rename(columns=
{'Member Name':'NOC_Grouping',
 'Member ID': 'NOC_GroupingID',  
})

df_Final_Tbl_NOC_Grouping_ID

,NOC_Grouping,NOC_GroupingID,Grouping Notes
17,"Total, all occupations",1,This combines the National Occupational Classi...
18,Management occupations,2,This combines the National Occupational Classi...
19,Legislative and senior management occupations,3,NaN
20,Specialized middle management occupations,4,This combines the National Occupational Classi...
21,Middle management occupations in retail and wh...,5,NaN
22,"Middle management occupations in trades, trans...",6,This combines the National Occupational Classi...
23,"Business, finance and administration occupatio...",7,This combines the National Occupational Classi...
24,Professional occupations in finance and business,8,NaN
25,Professional occupations in finance,9,NaN
26,Professional occupations in business,10,NaN
27,Administrative and financial supervisors and s...,11,NaN
28,Administrative occupations and transportation ...,12,NaN
29,Administrative and financial support and suppl...,13,NaN
30,Natural and applied sciences and related occup...,14,This combines the National Occupational Classi...
31,Professional occupations in natural and applie...,15,NaN
32,Professional occupations in natural sciences,16,NaN
33,Professional occupations in applied sciences (...,17,NaN
34,Professional occupations in engineering,18,NaN
35,Technical occupations related to natural and a...,19,NaN
36,"Health occupations, except management",20,This combines the National Occupational Classi...
37,Professional occupations in health,21,NaN
38,Health treating and consultation services prof...,22,NaN
39,Therapy and assessment professionals,23,NaN
40,Nursing and allied health professionals,24,NaN
41,Technical occupations in health,25,NaN
42,Assisting occupations in support of health ser...,26,NaN
43,"Occupations in education, law and social, comm...",27,This combines the National Occupational Classi...
44,"Professional occupations in law, education, so...",28,NaN
45,Professional occupations in law,29,NaN
46,Professional occupations in education services,30,NaN
47,Professional occupations in social and communi...,31,NaN
48,Professional occupations in government services,32,NaN
49,Front-line public protection services and para...,33,NaN
50,Occupations in front-line public protection se...,34,NaN
51,"Paraprofessional occupations in legal, social,...",35,NaN
52,Assisting occupations in education and in lega...,36,NaN
53,Care providers and public protection support o...,37,This combines the National Occupational Classi...
54,"Occupations in art, culture, recreation and sp...",38,This combines the National Occupational Classi...
55,Professional occupations in art and culture,39,NaN
56,"Technical occupations in art, culture and sport",40,NaN
57,"Occupations in art, culture and sport",41,NaN
58,"Support occupations in art, culture and sport",42,This combines the National Occupational Classi...
59,"Sales and service occupations, except management",43,This combines the National Occupational Classi...
60,Retail sales and service supervisors and speci...,44,NaN
61,Occupations in sales and services,45,NaN
62,Sales and service representatives and other cu...,46,NaN
63,Sales and service support occupations,47,NaN
64,"Trades, transport and equipment operators and ...",48,This combines the National Occupational Classi...
65,Technical trades and transportation officers a...,49,NaN
66,General trades,50,NaN
67,"Mail and message distribution, other transport...",51,NaN
68,Helpers and labourers and other transport driv...,52,NaN
69,"Natural resources, agriculture and related pro...",53,This combines the National Occupational Classi...
70,Supervisors and occupations in natural resourc...,54,This combines the National Occupational Classi...
71,"Workers and labourers in natural resources, ag...",55,This combines the National Occupational Classi...
72,"Occupations in manufacturing and utilities, ex...",56,This combines the National Occupational Classi...
73,"Supervisors, central control and process opera...",57,This combines the National Occupational Classi...
74,"Machine operators, assemblers and inspectors i...",58,NaN
75,"Labourers in processing, manufacturing and uti...",59,NaN
76,Unclassified occupations,60,Unemployed persons who have never worked befor...

In [12]:
df_Final_Tbl_NOC_Grouping_ID['Grouping Notes'] = df_Final_Tbl_NOC_Grouping_ID['Grouping Notes'].fillna('No Notes')
df_Final_Tbl_NOC_Grouping_ID

,NOC_Grouping,NOC_GroupingID,Grouping Notes
17,"Total, all occupations",1,This combines the National Occupational Classi...
18,Management occupations,2,This combines the National Occupational Classi...
19,Legislative and senior management occupations,3,No Notes
20,Specialized middle management occupations,4,This combines the National Occupational Classi...
21,Middle management occupations in retail and wh...,5,No Notes
22,"Middle management occupations in trades, trans...",6,This combines the National Occupational Classi...
23,"Business, finance and administration occupatio...",7,This combines the National Occupational Classi...
24,Professional occupations in finance and business,8,No Notes
25,Professional occupations in finance,9,No Notes
26,Professional occupations in business,10,No Notes
27,Administrative and financial supervisors and s...,11,No Notes
28,Administrative occupations and transportation ...,12,No Notes
29,Administrative and financial support and suppl...,13,No Notes
30,Natural and applied sciences and related occup...,14,This combines the National Occupational Classi...
31,Professional occupations in natural and applie...,15,No Notes
32,Professional occupations in natural sciences,16,No Notes
33,Professional occupations in applied sciences (...,17,No Notes
34,Professional occupations in engineering,18,No Notes
35,Technical occupations related to natural and a...,19,No Notes
36,"Health occupations, except management",20,This combines the National Occupational Classi...
37,Professional occupations in health,21,No Notes
38,Health treating and consultation services prof...,22,No Notes
39,Therapy and assessment professionals,23,No Notes
40,Nursing and allied health professionals,24,No Notes
41,Technical occupations in health,25,No Notes
42,Assisting occupations in support of health ser...,26,No Notes
43,"Occupations in education, law and social, comm...",27,This combines the National Occupational Classi...
44,"Professional occupations in law, education, so...",28,No Notes
45,Professional occupations in law,29,No Notes
46,Professional occupations in education services,30,No Notes
47,Professional occupations in social and communi...,31,No Notes
48,Professional occupations in government services,32,No Notes
49,Front-line public protection services and para...,33,No Notes
50,Occupations in front-line public protection se...,34,No Notes
51,"Paraprofessional occupations in legal, social,...",35,No Notes
52,Assisting occupations in education and in lega...,36,No Notes
53,Care providers and public protection support o...,37,This combines the National Occupational Classi...
54,"Occupations in art, culture, recreation and sp...",38,This combines the National Occupational Classi...
55,Professional occupations in art and culture,39,No Notes
56,"Technical occupations in art, culture and sport",40,No Notes
57,"Occupations in art, culture and sport",41,No Notes
58,"Support occupations in art, culture and sport",42,This combines the National Occupational Classi...
59,"Sales and service occupations, except management",43,This combines the National Occupational Classi...
60,Retail sales and service supervisors and speci...,44,No Notes
61,Occupations in sales and services,45,No Notes
62,Sales and service representatives and other cu...,46,No Notes
63,Sales and service support occupations,47,No Notes
64,"Trades, transport and equipment operators and ...",48,This combines the National Occupational Classi...
65,Technical trades and transportation officers a...,49,No Notes
66,General trades,50,No Notes
67,"Mail and message distribution, other transport...",51,No Notes
68,Helpers and labourers and other transport driv...,52,No Notes
69,"Natural resources, agriculture and related pro...",53,This combines the National Occupational Classi...
70,Supervisors and occupations in natural resourc...,54,This combines the National Occupational Classi...
71,"Workers and labourers in natural resources, ag...",55,This combines the National Occupational Classi...
72,"Occupations in manufacturing and utilities, ex...",56,This combines the National Occupational Classi...
73,"Supervisors, central control and process opera...",57,This combines the National Occupational Classi...
74,"Machine operators, assemblers and inspectors i...",58,No Notes
75,"Labourers in processing, manufacturing and uti...",59,No Notes
76,Unclassified occupations,60,Unemployed persons who have never worked befor...

In [15]:
df_Final_Tbl_NOC_Grouping_ID.to_csv('processed_data/Tbl_NOC_TS_Groupings.csv', index=False)